appConfig:
  app:
    name: just-meal
    port: 8080
  owner: justsquad
dbConfig:
  type: postgres
  postgres:
    host: localhost
    port: 5432
    user: user
    password: password
    dbname: dishes
  mongo:
    uri: mongodb://host1:27017
    database: dishes
